unique_ids:
  assets:
    standard-page.html: UPQ5BKG36KKPHPOU22OSUBL3OJHVMIOT
    theme.css: MFSOSDV6M4QEAZ6WKTQWIGRKO7OZQWEM
  forms:
    Form1: 42VPIR46PA3PQXJXGM4OLYYLROXJXSAH
  modules: {}
  scripts: {}
  server_modules: {}
